### ISSUE TITLE
edge disparity (metrics.py)

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/pelote#3]

**Comment by bmaz** [comment]
todo: raise if multigraph

**Comment by Yomguithereal** [comment]
todo: use networkx builtins for easy weighted degree

**Comment by bmaz** [comment]
add metric to scripts/docs.py

**Comment by bmaz** [comment]
check that networkx iterate on adjacency

**Comment by bmaz** [comment]
- [ ] add full definition with reference to paper

**Comment by Yomguithereal** [comment]
We need to discuss the directed case also and maybe bench a networkx edge iteration that we can do better (they rely on sets, the fools...)
